version: '3'
services:
    web:
        image: nginx:stable-alpine
        volumes:
            - ./web/default.conf:/etc/nginx/conf.d/default.conf
            - ./web/ssl:/etc/ssl
            - ./www:/var/www/html
            - ./web/default.template.conf:/etc/nginx/conf.d/default.template
        ports:
            - ${HTTP_PORT}:80
            - ${HTTPS_PORT}:443
        environment:
            - WEB_HOST=${WEB_HOST}
        command: /bin/sh -c "envsubst '$$WEB_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        restart: always
        depends_on:
            - php-fpm
            - php-cli
            - mysql
    php-fpm:
        build: ./build/php-fpm
        restart: always
        volumes:
            - ./php/fpm/:/usr/local/etc/php/conf.d/
            - ./www:/var/www/html
    php-cli:
        build: ./build/php-cli
        volumes:
            - ./php/cli/:/usr/local/etc/php/conf.d/
            - ./www:/var/www/html
    composer:
        image: composer
        volumes:
            - ./www:/app
        command: install
    adminer:
        image: adminer
        ports:
            - ${ADMINER_PORT}:8080
        restart: always
        depends_on:
            - mysql
    mysql:
        build: ./build/mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        env_file:
            - .env
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - ${MYSQL_PORT}:3306
