version: '3'
services:
    web:
        image: nginx:stable-alpine
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/ssl:/etc/ssl
            - ./www:/var/www/html
            - ./nginx/default.template.conf:/etc/nginx/conf.d/default.template
        ports: 
            - 80:80
            - 443:443
        environment:
            - NGINX_HOST=${NGINX_HOST}
        command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        restart: always
        depends_on:
            - php-fpm
            - php-cli
            - mysql
    php-fpm:
        build: ./build/php-fpm
        restart: always
        volumes:
            - ./php/fpm/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./www:/var/www/html
    php-cli:
        build: ./build/php-cli
        restart: always
        volumes:
            - ./php/cli/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./www:/var/www/html
    composer:
        image: composer
        volumes:
            - ./www/app:/app
    adminer:
        image: adminer
        ports:
            - 8080:80
        restart: always
        depends_on:
            - mysql
    mysql:
        image: mysql:${MYSQL_VERSION}
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        env_file:
            - .env
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - 3306:3306
        volumes:
            - ./mysql/db:/var/lib/mysql